sudo: required
services: 
 - docker

before_install: 
  - docker build -t jesquivel2/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true cpavlatos/react-test npm test

after_success:
  - docker build -t jesquivel2/multi-client ./client
  - docker build -t jesquivel2/multi-nginx ./nginx
  - docker build -t jesquivel2/multi-server ./server
  - docker build -t jesquivel2/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jesquivel2/multi-client
  - docker push jesquivel2/multi-nginx
  - docker push jesquivel2/multi-server
  - docker push jesquivel2/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-277207955094
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY